# Generated by Django 2.1.2 on 2019-09-28 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_commented_by', to='social.Profile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_post_by', to='social.Post'),
        ),
        migrations.AlterField(
            model_name='followuser',
            name='followe_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_follow_by', to='social.Profile'),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_like_by', to='social.Profile'),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_post', to='social.Profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_upload_by', to='social.Profile'),
        ),
    ]
